// React applikation/react_projekthanterare/src/components/ProjektObjekt.jsx
import "../pages/Projekt/Projekt.css"

function ProjektObjekt({namn, startDatum, slutDatum, prioritet}){
    return(
        <tr>
            <td className= "projektObjekt">{namn}</td>
            <td className= "projektObjekt">{startDatum}</td>
            <td className= "projektObjekt">{slutDatum}</td>
            <td className= "projektObjekt">{prioritet}</td>
        </tr>
    )
   
}

export default ProjektObjekt;

// Svelte applikation/svelte_projekthanterare/src/lib/components/ProjektObjekt.svelte
<script>
    let {namn, startDatum, slutDatum, prioritet} = $props();
</script>

 <tr>
    <td class= "projektObjekt">{namn}</td>
    <td class= "projektObjekt">{startDatum}</td>
    <td class= "projektObjekt">{slutDatum}</td>
    <td class= "projektObjekt">{prioritet}</td>
</tr>

<style>
    tr:nth-child(even) {background-color: #e8e8e8;
}
tr:hover{
    background-color: #adadad;
}

.projektObjekt{
    border-collapse: collapse;
    border: 1px solid rgb(100, 100, 100)
}

</style>
